s3:
    bucket_name: 'capston'

image_settings:
    horizontal_res: 1024
    vertical_res: 768
    file_name: 'CDF'
    file_extension: '.jpg'
    folder_name: 'images'
    awb_mode: 'auto'
    photo_interval: 5

debug: true



